pretrained_base_model_path: '/mnt/petrelfs/liuwenran/.cache/huggingface/hub/models--lambdalabs--sd-image-variations-diffusers/snapshots/42bc0ee1726b141d49f519a6ea02ccfbf073db2e'
pretrained_vae_path: "./pretrained_weights/sd-vae-ft-mse"
image_encoder_path: '/mnt/petrelfs/liuwenran/.cache/huggingface/hub/models--lambdalabs--sd-image-variations-diffusers/snapshots/42bc0ee1726b141d49f519a6ea02ccfbf073db2e/image_encoder'
# denoising_unet_path: "./pretrained_weights/denoising_unet.pth"
# reference_unet_path: "./pretrained_weights/reference_unet.pth"
# pose_guider_path: "./pretrained_weights/pose_guider.pth"
# motion_module_path: "./pretrained_weights/motion_module.pth"

# ckpt_tuned_path: '/mnt/petrelfs/liuwenran/forks/Moore-AnimateAnyone/exp_output/stage1/checkpoint-30000/model.safetensors'
# ckpt_tuned_path: '/mnt/petrelfs/liuwenran/forks/Moore-AnimateAnyone/exp_output/stage1_weiqishaonian/checkpoint-18000/model.safetensors'
ckpt_tuned_path: '/mnt/petrelfs/liuwenran/repos/HumanAnimation/exp_output/stage1_5100_hed/checkpoint-40000/model.safetensors'

inference_config: 'configs/inference/inference_img.yaml'
weight_dtype: 'fp16'

unet_additional_kwargs:
  use_inflated_groupnorm: true
  unet_use_cross_frame_attention: false 
  unet_use_temporal_attention: false
  use_motion_module: false

noise_scheduler_kwargs:
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: "linear"
  clip_sample: false
  steps_offset: 1
  ### Zero-SNR params
  prediction_type: "v_prediction"
  rescale_betas_zero_snr: True
  timestep_spacing: "trailing"

sampler: DDIM 

first_ref_image: /mnt/petrelfs/liuwenran/datasets/cctv/changeface/shierchangsheng_test_7_mmagic_512/0001.png
# first_ref_image: /mnt/petrelfs/liuwenran/datasets/cctv/changeface/shierchangsheng_woman_ref/woman_ref_768.png
validate_control_image_file: /mnt/petrelfs/liuwenran/datasets/cctv/changeface/shierchangsheng_test_7.txt
# validate_control_image_file: /mnt/petrelfs/liuwenran/datasets/cctv/changeface/shierchangsheng_test_7_crop_woman.txt
save_path: /mnt/petrelfs/liuwenran/datasets/cctv/changeface/shierchangsheng_moore_aa_crop_woman_512_weiqishaonian_combine5100


