pretrained_base_model_path: '/mnt/petrelfs/liuwenran/.cache/huggingface/hub/models--stabilityai--stable-diffusion-xl-base-1.0/snapshots/462165984030d82259a11f4367a4eed129e94a7b'
pretrained_vae_path: "/mnt/petrelfs/liuwenran/.cache/huggingface/hub/models--madebyollin--sdxl-vae-fp16-fix/snapshots/4df413ca49271c25289a6482ab97a433f8117d15"
image_encoder_path: '/mnt/petrelfs/liuwenran/.cache/huggingface/hub/models--h94--IP-Adapter/snapshots/92a2d51861c754afacf8b3aaf90845254b49f219'
# denoising_unet_path: "./pretrained_weights/denoising_unet.pth"
# reference_unet_path: "./pretrained_weights/reference_unet.pth"
# pose_guider_path: "./pretrained_weights/pose_guider.pth"
# motion_module_path: "./pretrained_weights/motion_module.pth"

# ckpt_tuned_path: '/mnt/petrelfs/liuwenran/forks/Moore-AnimateAnyone/exp_output/stage1/checkpoint-30000/model.safetensors'
# ckpt_tuned_path: '/mnt/petrelfs/liuwenran/forks/Moore-AnimateAnyone/exp_output/stage1_weiqishaonian/checkpoint-20000/model.safetensors'
# ckpt_tuned_path: '/mnt/petrelfs/liuwenran/forks/Moore-AnimateAnyone/exp_output/stage1_sdxl_5100_tune_denoising/checkpoint-30000/model.safetensors'
# ckpt_tuned_path: '/mnt/petrelfs/liuwenran/forks/Moore-AnimateAnyone/exp_output/stage1_sdxl_5100/checkpoint-30000/model.safetensors'
# ckpt_tuned_path: '/mnt/petrelfs/liuwenran/forks/Moore-AnimateAnyone/exp_output/stage1_sdxl_5100_tuneall/checkpoint-40000/model.safetensors'
ckpt_tuned_path: '/mnt/petrelfs/liuwenran/forks/Moore-AnimateAnyone/exp_output/stage1_sdxl_5100_tuneall_downmid-up0a0/checkpoint-40000/model.safetensors'

# denoising_unet_path: /mnt/petrelfs/liuwenran/forks/Moore-AnimateAnyone/exp_output/stage1_sdxl_5100_tune_denoising/denoising_unet-28890.pth
# reference_unet_path: /mnt/petrelfs/liuwenran/forks/Moore-AnimateAnyone/exp_output/stage1_sdxl_5100_tune_denoising/reference_unet-28890.pth
# pose_guider_path: /mnt/petrelfs/liuwenran/forks/Moore-AnimateAnyone/exp_output/stage1_sdxl_5100_tune_denoising/pose_guider-28890.pth
# denoising_unet_path: /mnt/petrelfs/liuwenran/forks/Moore-AnimateAnyone/exp_output/stage1_sdxl_5100_tuneall/denoising_unet-6410.pth
# reference_unet_path: /mnt/petrelfs/liuwenran/forks/Moore-AnimateAnyone/exp_output/stage1_sdxl_5100_tuneall/reference_unet-6410.pth
# pose_guider_path: /mnt/petrelfs/liuwenran/forks/Moore-AnimateAnyone/exp_output/stage1_sdxl_5100_tuneall/pose_guider-6410.pth

weight_dtype: 'fp16'

unet_additional_kwargs:
  use_inflated_groupnorm: true
  unet_use_cross_frame_attention: false 
  unet_use_temporal_attention: false
  use_motion_module: false

noise_scheduler_kwargs:
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: "linear"
  clip_sample: false
  steps_offset: 1
  ### Zero-SNR params
  prediction_type: "v_prediction"
  rescale_betas_zero_snr: True
  timestep_spacing: "trailing"

sampler: DDIM 

validate_image_file: /mnt/petrelfs/liuwenran/forks/Moore-AnimateAnyone/data/validate_pair_images.txt
validate_control_image_file: /mnt/petrelfs/liuwenran/forks/Moore-AnimateAnyone/data/validate_pair_images_part_two.txt

fusion_type: 'downmid-up0a0'
